FROM nvidia/cuda
RUN apt update -y
RUN apt upgrade -y
RUN apt install git -y
RUN apt install curl -y
WORKDIR /home
RUN git clone https://git.videolan.org/git/ffmpeg/nv-codec-headers.git
WORKDIR nv-codec-headers
RUN make
RUN make install
WORKDIR /home
RUN apt install pkgconf -y
RUN git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg/
RUN apt install -y build-essential yasm cmake libtool libc6 libc6-dev unzip wget libnuma1 libnuma-dev
WORKDIR ffmpeg
RUN ./configure --enable-nonfree --enable-nvenc --enable-cuda --enable-cuvid --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64
RUN make -j 8
RUN make install
WORKDIR /home
